Trying to fix the SectionTest UI test which breaks from time to time with an error of:
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"tmCurrentEditor"}
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.27.10-grsec-xxxx-grs-ipv4-64', java.version: '1.5.0_15'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:494)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:131)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:105)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:395)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:183)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:200)
	at org.openqa.selenium.By$1.findElement(By.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:175)
	at org.xwiki.test.ui.framework.elements.BasePage.hoverOverMenu(BasePage.java:106)
	at org.xwiki.test.ui.framework.elements.editor.EditPage.clickContentMenuEditSubMenuEntry(EditPage.java:170)
	at org.xwiki.test.ui.framework.elements.BasePage.editWiki(BasePage.java:162)
	at org.xwiki.test.ui.SectionTest.testSectionEditInWikiEditorWhenSyntax20(SectionTest.java:129)